In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
listings = pd.read_csv("C:\\Users\\satya\\Downloads\\listings.csv.gz")
calendar = pd.read_csv("C:\\Users\\satya\\Downloads\\calendar.csv.gz")

print("listings shape:", listings.shape)
print("calendar shape:", calendar.shape)

print("\nlistings columns sample:", listings.columns[:15].tolist())
print("\ncalendar columns sample:", calendar.columns[:15].tolist())

listings.head(3)
calendar.head(3)

listings shape: (36261, 85)
calendar shape: (13235283, 7)

listings columns sample: ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_since']

calendar columns sample: ['listing_id', 'date', 'available', 'price', 'adjusted_price', 'minimum_nights', 'maximum_nights']

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2539,2025-12-06,t,NaN,NaN,30,730
1,2539,2025-12-07,t,NaN,NaN,30,730
2,2539,2025-12-08,t,NaN,NaN,30,730

In [31]:
important_cols = [
    "id",
    "neighbourhood_group_cleansed",
    "neighbourhood_cleansed",
    "room_type",
    "property_type",
    "accommodates",
    "bedrooms",
    "bathrooms_text",
    "minimum_nights",
    "number_of_reviews",
    "review_scores_rating",
    "availability_365",
    "calculated_host_listings_count",
    "reviews_per_month",
    "price"
]

# Keep only columns that actually exist
cols_to_keep = [col for col in important_cols if col in listings.columns]

listings_small = listings[cols_to_keep].copy()

print("Selected columns:")
print(listings_small.columns.tolist())

print("\nNew shape:", listings_small.shape)

listings_small.head(3)

Selected columns:
['id', 'neighbourhood_group_cleansed', 'neighbourhood_cleansed', 'room_type', 'property_type', 'accommodates', 'bedrooms', 'bathrooms_text', 'minimum_nights', 'number_of_reviews', 'review_scores_rating', 'availability_365', 'calculated_host_listings_count', 'reviews_per_month', 'price']

New shape: (36261, 15)

,id,neighbourhood_group_cleansed,neighbourhood_cleansed,room_type,property_type,accommodates,bedrooms,bathrooms_text,minimum_nights,number_of_reviews,review_scores_rating,availability_365,calculated_host_listings_count,reviews_per_month,price
0,2539,Brooklyn,Kensington,Private room,Private room in condo,2,1.0,1 shared bath,30,9,4.89,364,7,0.07,NaN
1,2595,Manhattan,Midtown,Entire home/apt,Entire rental unit,1,0.0,1 bath,30,47,4.68,319,3,0.24,NaN
2,6848,Brooklyn,Williamsburg,Entire home/apt,Entire rental unit,3,2.0,1 bath,30,197,4.60,261,1,0.98,NaN

In [32]:
print("Total rows:", len(listings_small))
print("Missing price values:", listings_small["price"].isna().sum())
print("Percentage missing:", 
      round(100 * listings_small["price"].isna().sum() / len(listings_small), 2), "%")

Total rows: 36261
Missing price values: 36261
Percentage missing: 100.0 %

In [33]:
# Check missing price in calendar
print("Calendar rows:", len(calendar))
print("Missing calendar price:", calendar["price"].isna().sum())

calendar.head(3)

Calendar rows: 13235283
Missing calendar price: 13235283

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2539,2025-12-06,t,NaN,NaN,30,730
1,2539,2025-12-07,t,NaN,NaN,30,730
2,2539,2025-12-08,t,NaN,NaN,30,730

In [34]:
print("Total calendar rows:", len(calendar))

print("\nMissing price:", calendar["price"].isna().sum())
print("Missing adjusted_price:", calendar["adjusted_price"].isna().sum())

print("\nNon-missing price count:", calendar["price"].notna().sum())
print("Non-missing adjusted_price count:", calendar["adjusted_price"].notna().sum())

Total calendar rows: 13235283

Missing price: 13235283
Missing adjusted_price: 13235283

Non-missing price count: 0
Non-missing adjusted_price count: 0

In [35]:
print(calendar.dtypes)

print("\nSample raw price values (first 10):")
print(calendar["price"].head(10).tolist())

print("\nSample raw adjusted_price values (first 10):")
print(calendar["adjusted_price"].head(10).tolist())

print("\nUnique values count in price:", calendar["price"].nunique(dropna=False))
print("Unique values count in adjusted_price:", calendar["adjusted_price"].nunique(dropna=False))

listing_id          int64
date               object
available          object
price             float64
adjusted_price    float64
minimum_nights      int64
maximum_nights      int64
dtype: object

Sample raw price values (first 10):
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

Sample raw adjusted_price values (first 10):
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

Unique values count in price: 1
Unique values count in adjusted_price: 1

In [36]:
# restart from begining with new datset from kaggle

In [37]:
import pandas as pd

df = pd.read_csv("C:\\Users\\satya\\Downloads\\archive (1)\\AB_NYC_2019.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head(3)

Shape: (48895, 16)

Columns:
['id', 'name', 'host_id', 'host_name', 'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [39]:
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [40]:
df_clean = df.drop(columns=["name", "host_name", "last_review"])

print("New shape:", df_clean.shape)
df_clean.head(3)

New shape: (48895, 13)

,id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,2595,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,3647,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,1,365

In [41]:
df_clean["reviews_per_month"] = df_clean["reviews_per_month"].fillna(0)

print("Missing reviews_per_month:", df_clean["reviews_per_month"].isna().sum())
df_clean.head(3)

Missing reviews_per_month: 0

,id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,2595,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,3647,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0.00,1,365

In [42]:
df_clean["price"].describe()

count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [43]:
df_clean.sort_values("price", ascending=False).head(10)

,id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
29238,22436899,72390391,Manhattan,Upper West Side,40.77213,-73.98665,Entire home/apt,10000,30,0,0.00,1,83
9151,7003697,20582832,Queens,Astoria,40.76810,-73.91651,Private room,10000,100,2,0.04,1,0
17692,13894339,5143901,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,0.16,1,0
6530,4737930,1235070,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,0.02,1,0
40433,31340283,4382127,Manhattan,Lower East Side,40.71980,-73.98566,Entire home/apt,9999,30,0,0.00,1,365
12342,9528920,3906464,Manhattan,Lower East Side,40.71355,-73.98507,Private room,9999,99,6,0.14,1,83
30268,23377410,18128455,Manhattan,Tribeca,40.72197,-74.00633,Entire home/apt,8500,30,2,0.18,1,251
4377,2953058,1177497,Brooklyn,Clinton Hill,40.69137,-73.96723,Entire home/apt,8000,1,1,0.03,11,365
29662,22779726,156158778,Manhattan,Upper East Side,40.76824,-73.95989,Entire home/apt,7703,1,0,0.00,12,146
42523,33007610,7407743,Manhattan,Battery Park City,40.71162,-74.01693,Entire home/apt,7500,1,0,0.00,1,364

In [44]:
p99 = df_clean["price"].quantile(0.99)
print("99th percentile price:", p99)

99th percentile price: 799.0

In [45]:
df_clean = df_clean[(df_clean["price"] > 0) & (df_clean["price"] <= 799)]

print("New shape after removing outliers:", df_clean.shape)
df_clean["price"].describe()

New shape after removing outliers: (48410, 13)

count    48410.000000
mean       137.575170
std        103.780081
min         10.000000
25%         69.000000
50%        105.000000
75%        175.000000
max        799.000000
Name: price, dtype: float64

In [46]:
df_model = df_clean.drop(columns=["id", "host_id"])

print("Columns used for model:")
print(df_model.columns.tolist())

print("\nShape:", df_model.shape)

Columns used for model:
['neighbourhood_group', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

Shape: (48410, 11)

In [47]:
X = df_model.drop(columns=["price"])
y = df_model["price"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

X.head(3)

Feature shape: (48410, 10)
Target shape: (48410,)

,neighbourhood_group,neighbourhood,latitude,longitude,room_type,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,Brooklyn,Kensington,40.64749,-73.97237,Private room,1,9,0.21,6,365
1,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,0.38,2,355
2,Manhattan,Harlem,40.80902,-73.94190,Private room,3,0,0.00,1,365

In [48]:
print("Categorical columns:")
print(X.select_dtypes(include="object").columns.tolist())

print("\nNumerical columns:")
print(X.select_dtypes(exclude="object").columns.tolist())

Categorical columns:
['neighbourhood_group', 'neighbourhood', 'room_type']

Numerical columns:
['latitude', 'longitude', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

In [49]:
X_encoded = pd.get_dummies(X, drop_first=True)

print("New shape after encoding:", X_encoded.shape)
X_encoded.head(3)

New shape after encoding: (48410, 232)

,latitude,longitude,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,neighbourhood_group_Brooklyn,neighbourhood_group_Manhattan,neighbourhood_group_Queens,...,neighbourhood_Williamsbridge,neighbourhood_Williamsburg,neighbourhood_Willowbrook,neighbourhood_Windsor Terrace,neighbourhood_Woodhaven,neighbourhood_Woodlawn,neighbourhood_Woodrow,neighbourhood_Woodside,room_type_Private room,room_type_Shared room
0,40.64749,-73.97237,1,9,0.21,6,365,True,False,False,...,False,False,False,False,False,False,False,False,True,False
1,40.75362,-73.98377,1,45,0.38,2,355,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,40.80902,-73.94190,3,0,0.00,1,365,False,True,False,...,False,False,False,False,False,False,False,False,True,False

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, 
    test_size=0.2, 
    random_state=42
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (38728, 232)
Testing set shape: (9682, 232)

In [51]:
from sklearn.linear_model import LinearRegression

# Create model
lr_model = LinearRegression()

# Train model
lr_model.fit(X_train, y_train)

print("Model training completed.")

Model training completed.

In [52]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predict on test set
y_pred = lr_model.predict(X_test)

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R2 Score:", round(r2, 4))

MAE: 50.25
RMSE: 80.23
R2 Score: 0.4085

In [53]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest training completed.")

Random Forest training completed.

In [54]:
# Predict using Random Forest
y_pred_rf = rf_model.predict(X_test)

# Calculate metrics
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Results")
print("MAE:", round(mae_rf, 2))
print("RMSE:", round(rmse_rf, 2))
print("R2 Score:", round(r2_rf, 4))

Random Forest Results
MAE: 44.86
RMSE: 72.82
R2 Score: 0.5127

In [56]:
import xgboost as xgb
print("XGBoost version:", xgb.__version__)

XGBoost version: 3.2.0

In [57]:
import numpy as np

# Log transform target
y_log = np.log1p(y)

print("Original price sample:", y.head(5).values)
print("Log-transformed sample:", y_log.head(5).values)

Original price sample: [149 225 150  89  80]
Log-transformed sample: [5.01063529 5.420535   5.01727984 4.49980967 4.39444915]

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_log, y_test_log = train_test_split(
    X_encoded, y_log,
    test_size=0.2,
    random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: (38728, 232)
Testing shape: (9682, 232)

In [59]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

# Train using log target
xgb_model.fit(X_train, y_train_log)

print("XGBoost training completed.")

XGBoost training completed.

In [60]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predict in log scale
y_pred_log = xgb_model.predict(X_test)

# Convert back to normal price
y_pred = np.expm1(y_pred_log)
y_true = np.expm1(y_test_log)

# Evaluate
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("XGBoost Results (back to price scale)")
print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R2 Score:", round(r2, 4))

XGBoost Results (back to price scale)
MAE: 42.46
RMSE: 74.27
R2 Score: 0.4932

In [61]:
# Predict using Random Forest on entire dataset
df_model["ml_predicted_price"] = rf_model.predict(X_encoded)

df_model[["price", "ml_predicted_price"]].head()

   price  ml_predicted_price
0    149              128.71
1    225              346.52
2    150              133.26
3     89              110.68
4     80              151.10

In [62]:
# Occupancy proxy (lower availability = higher demand)
df_model["occupancy_proxy"] = 1 - (df_model["availability_365"] / 365)

# Normalize number_of_reviews
df_model["reviews_norm"] = (
    df_model["number_of_reviews"] - df_model["number_of_reviews"].min()
) / (
    df_model["number_of_reviews"].max() - df_model["number_of_reviews"].min()
)

# Create demand index (weighted)
df_model["demand_index"] = (
    0.6 * df_model["occupancy_proxy"] +
    0.4 * df_model["reviews_norm"]
)

df_model[["occupancy_proxy", "reviews_norm", "demand_index"]].head()

   occupancy_proxy  reviews_norm  demand_index
0         0.000000      0.014308      0.005723
1         0.027397      0.071542      0.045055
2         0.000000      0.000000      0.000000
3         0.468493      0.429253      0.452797
4         1.000000      0.014308      0.605723

In [63]:
# Define max dynamic adjustment (30%)
max_adjustment = 0.30

# Calculate dynamic suggested price
df_model["dynamic_suggested_price"] = (
    df_model["ml_predicted_price"] *
    (1 + df_model["demand_index"] * max_adjustment)
)

df_model[["price", "ml_predicted_price", "demand_index", "dynamic_suggested_price"]].head()

   price  ml_predicted_price  demand_index  dynamic_suggested_price
0    149              128.71      0.005723               128.930997
1    225              346.52      0.045055               351.203759
2    150              133.26      0.000000               133.260000
3     89              110.68      0.452797               125.714672
4     80              151.10      0.605723               178.557440

In [64]:
# Calculate uplift %
df_model["uplift_percentage"] = (
    (df_model["dynamic_suggested_price"] - df_model["price"])
    / df_model["price"]
) * 100

df_model[["price", "dynamic_suggested_price", "uplift_percentage"]].head()

   price  dynamic_suggested_price  uplift_percentage
0    149               128.930997          -13.46913
1    225               351.203759           56.09056
2    150               133.260000          -11.16000
3     89               125.714672           41.25244
4     80               178.557440          123.19680

In [65]:
# Average uplift
avg_uplift = df_model["uplift_percentage"].mean()

# Listings that can increase price
increase_count = (df_model["uplift_percentage"] > 5).sum()

# Listings that should reduce price
decrease_count = (df_model["uplift_percentage"] < -5).sum()

print("Average Uplift %:", round(avg_uplift, 2))
print("Listings with Increase Opportunity:", increase_count)
print("Listings Overpriced (Should Reduce):", decrease_count)

Average Uplift %: 23.06
Listings with Increase Opportunity: 36661
Listings Overpriced (Should Reduce): 4977

In [66]:
# Cap uplift at -50% and +50%
df_model["uplift_capped"] = df_model["uplift_percentage"].clip(-50, 50)

# Recalculate final recommended price based on capped uplift
df_model["final_recommended_price"] = (
    df_model["price"] * (1 + df_model["uplift_capped"] / 100)
)

df_model[["price", "uplift_percentage", "uplift_capped", "final_recommended_price"]].head()

   price  uplift_percentage  uplift_capped  final_recommended_price
0    149          -13.46913      -13.46913               128.930997
1    225           56.09056       50.00000               337.500000
2    150          -11.16000      -11.16000               133.260000
3     89           41.25244       41.25244               125.714672
4     80          123.19680       50.00000               120.000000

In [67]:
comparison = pd.DataFrame({
    "Current_Avg_Price": [df_model["price"].mean()],
    "ML_Base_Avg_Price": [df_model["ml_predicted_price"].mean()],
    "Dynamic_Avg_Price": [df_model["dynamic_suggested_price"].mean()],
    "Final_Recommended_Avg": [df_model["final_recommended_price"].mean()]
})

comparison.round(2)

,Current_Avg_Price,ML_Base_Avg_Price,Dynamic_Avg_Price,Final_Recommended_Avg
0,137.58,138.54,155.63,152.84

In [68]:
df_model["pricing_category"] = np.where(
    df_model["uplift_capped"] > 5, "Increase Price",
    np.where(df_model["uplift_capped"] < -5, "Reduce Price", "Keep Same")
)

df_model["pricing_category"].value_counts()

pricing_category
Increase Price    36661
Keep Same          6772
Reduce Price       4977
Name: count, dtype: int64

In [69]:
borough_analysis = df_model.groupby("neighbourhood_group")[
    ["price", "final_recommended_price", "uplift_capped"]
].mean()

borough_analysis.round(2)

                      price  final_recommended_price  uplift_capped
neighbourhood_group
Bronx                 83.86                    91.46          17.76
Brooklyn             115.92                   129.82          19.54
Manhattan            172.90                   191.66          18.65
Queens                94.10                   103.13          17.08
Staten Island         94.24                   100.08          16.57

In [70]:
print("Current Avg Price:", round(df_model["price"].mean(), 2))
print("ML Base Avg Price:", round(df_model["ml_predicted_price"].mean(), 2))
print("Dynamic Avg Price:", round(df_model["dynamic_suggested_price"].mean(), 2))
print("Final Recommended Avg Price:", round(df_model["final_recommended_price"].mean(), 2))

Current Avg Price: 137.58
ML Base Avg Price: 138.54
Dynamic Avg Price: 155.63
Final Recommended Avg Price: 152.84

In [71]:
import pandas as pd

feature_importance = pd.DataFrame({
    "feature": X_encoded.columns,
    "importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="importance", ascending=False
)

feature_importance.head(10)

                            feature  importance
230          room_type_Private room    0.230128
1                         longitude    0.182371
0                          latitude    0.149169
6                  availability_365    0.097848
4                 reviews_per_month    0.065922
2                    minimum_nights    0.060957
3                 number_of_reviews    0.054941
5    calculated_host_listings_count    0.043958
231           room_type_Shared room    0.026635
136           neighbourhood_Midtown    0.022865

In [72]:
df_model.to_csv("nyc_dynamic_pricing_final.csv", index=False)
print("Final dataset exported successfully.")

Final dataset exported successfully.